language: php
matrix:
  include:
  - php: "nightly"
    env: LEGACY=false
  - php: "7.0"
    env: LEGACY=false
  - php: "5.3.3"
    env: LEGACY=true
install:
  - cp example.env .env
  - if $LEGACY; then source ./tests/travis/install.legacy.bash;
    else source ./tests/travis/install.bash; fi
script:
  - ./tests/lint.bash
  - if $LEGACY; then source ./tests/travis/script.legacy.bash;
    else source ./tests/travis/script.bash; fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
