language: php
php:
  - 7.0.8
  - 5.6
  - 5.5.9
  - 5.3.3
install:
  - composer config -g -- disable-tls true
  - composer install --no-dev
  - cp example.env .env
script:
  - ./tests/lint.bash
  - phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
